baseURL = "https://depts.washington.edu/rauv/"
#baseURL = "http://staff.washington.edu/amarburg/cabled_array_hw2018/"
languageCode = "en-us"
title = "Resident AUV Workshop 2018"
theme = "ananke"

publishDir = "as_published/"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Resident AUV Workshop 2018"
  # facebook = ""
  #twitter = "https://twitter.com/GoHugoIO"
  # instagram = ""
  # youtube = ""
  # github = ""
  # linkedin = ""

  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/RAUV_header.jpg"
  recent_posts_number = 2

  custom_css = ["css/custom_table.css",
                "css/measure_wide.css",
                "css/pv6.css"]
